name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-11-jdk python3-pip \
            build-essential git libffi-dev libssl-dev \
            libjpeg-dev zlib1g-dev libncurses5 libstdc++6
        pip install --upgrade pip setuptools cython virtualenv
        pip install buildozer

    - name: Add buildozer.spec
      run: |
        buildozer init || true
        echo "source.include_exts = py,kv" >> buildozer.spec
        echo "requirements = python3,kivy,kivymd" >> buildozer.spec
        echo "android.permissions = INTERNET" >> buildozer.spec
        echo "title = JarvisApp" >> buildozer.spec
        echo "package.name = jarvis" >> buildozer.spec
        echo "package.domain = org.example" >> buildozer.spec

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: jarvis-apk
        path: bin/*.apk
